/** Re-exports zip-based location — legacy import path */
export {
  bootstrapCityIfNeeded,
  citySourceLabel,
  detectAndSaveCity,
  detectZipFromGps,
  getCitySource,
  getLocationDisplayLabel,
  getLocationTimezone,
  getPopitLocation,
  getResolvedCity,
  getStoredCity,
  getStoredZipCode,
  hasSeenLocationPrompt,
  hourInTimezone,
  inferCityFromTimezone,
  inferRegionFromTimezone,
  isValidZipCode,
  lookupZipCode,
  markLocationPromptSeen,
  normalizeProfileCity,
  normalizeZipInput,
  requestGeolocationPosition,
  saveTimezoneFallbackCity,
  saveZipCode,
  estimateTempFromLocation,
  CITY_UPDATED_EVENT,
  DEFAULT_CITY_LABEL,
  LEGACY_DEFAULT_CITY,
  type CitySource,
  type CityUpdatedDetail,
  type LocationSource,
  type PopitLocation,
} from "./zipLocation";
