import type { SocialState } from "./types";

const now = Date.now();
const h = (hours: number) => now - hours * 60 * 60 * 1000;

export const SEED_SOCIAL_STATE: SocialState = {
  following: ["neon-lounge", "dj-kairo", "pulse-kitchen", "marcus-j"],
  stories: [
    { id: "s-own", username: "you", name: "Your Story", accent: "#A855F7", viewed: false, isOwn: true, previewHue: "#A855F7" },
    { id: "s1", username: "neon-lounge", name: "Neon Lounge", accent: "#FF4D6D", verified: true, viewed: false, isLive: true, previewHue: "#FF4D6D" },
    { id: "s2", username: "dj-kairo", name: "KAIRO", accent: "#00D4FF", verified: true, viewed: false, previewHue: "#00D4FF" },
    { id: "s3", username: "pulse-kitchen", name: "Pulse Kitchen", accent: "#FFB020", verified: true, viewed: true, previewHue: "#FFB020" },
    { id: "s4", username: "marcus-j", name: "Marcus J", accent: "#34D399", verified: true, viewed: true, previewHue: "#34D399" },
    { id: "s5", username: "nova-games", name: "Nova", accent: "#A855F7", viewed: false, previewHue: "#A855F7" },
    { id: "s6", username: "miami-foodie", name: "Miami Foodie", accent: "#FF4D6D", verified: true, viewed: false, previewHue: "#FF4D6D" },
  ],
  posts: [
    {
      id: "p1",
      kind: "checkin",
      authorUsername: "neon-lounge",
      authorName: "Neon Lounge",
      authorAccent: "#FF4D6D",
      verified: true,
      live: true,
      title: "Almost full tonight",
      text: "Brickell is moving. Doors open · VIP lanes live on the map.",
      venue: "Neon Lounge · Brickell",
      city: "Miami",
      mediaHue: "#FF4D6D",
      createdAt: h(1),
      likes: 2840,
      comments: 186,
      reposts: 412,
      saves: 920,
      liked: false,
      saved: true,
      reposted: false,
      following: true,
    },
    {
      id: "p2",
      kind: "reel",
      authorUsername: "dj-kairo",
      authorName: "KAIRO",
      authorAccent: "#00D4FF",
      verified: true,
      live: true,
      text: "Main room set · 14K watching on the city map",
      venue: "LIV Nightclub",
      city: "Miami",
      mediaHue: "#00D4FF",
      createdAt: h(2),
      likes: 12400,
      comments: 890,
      reposts: 2100,
      saves: 3400,
      liked: true,
      saved: false,
      reposted: false,
      following: true,
      musicTrack: "City Pulse · POP'IT Originals",
    },
    {
      id: "p3",
      kind: "thought",
      authorUsername: "marcus-j",
      authorName: "Marcus J",
      authorAccent: "#34D399",
      verified: true,
      text: "South Beach energy is different when the whole city can see the wave building in real time. POP'IT nailed the vibe.",
      city: "Miami",
      createdAt: h(3),
      likes: 892,
      comments: 64,
      reposts: 128,
      saves: 45,
      liked: false,
      saved: false,
      reposted: true,
      following: true,
    },
    {
      id: "p4",
      kind: "page",
      authorUsername: "pulse-kitchen",
      authorName: "Pulse Kitchen",
      authorAccent: "#FFB020",
      verified: true,
      title: "Wynwood dinner rush",
      text: "+344 people checked in tonight. Chef's tasting still available until midnight.",
      venue: "Pulse Kitchen · Wynwood",
      city: "Miami",
      mediaHue: "#FFB020",
      createdAt: h(5),
      likes: 1560,
      comments: 98,
      reposts: 210,
      saves: 380,
      liked: true,
      saved: false,
      reposted: false,
      following: true,
    },
    {
      id: "p5",
      kind: "thought",
      authorUsername: "miami-foodie",
      authorName: "Miami Foodie",
      authorAccent: "#FF4D6D",
      verified: true,
      text: "If you're not on the city map tonight you're missing the whole point 🌴 #MiamiEats #WhatsPopping",
      city: "Miami",
      createdAt: h(6),
      likes: 4200,
      comments: 312,
      reposts: 890,
      saves: 120,
      liked: false,
      saved: false,
      reposted: false,
      following: false,
    },
    {
      id: "p6",
      kind: "reel",
      authorUsername: "nova-games",
      authorName: "Nova",
      authorAccent: "#A855F7",
      text: "Ranked grind then rooftop — Wynwood Walk trending on the feed",
      venue: "Wynwood Walls",
      city: "Miami",
      mediaHue: "#A855F7",
      createdAt: h(8),
      likes: 6800,
      comments: 445,
      reposts: 670,
      saves: 890,
      liked: false,
      saved: true,
      reposted: false,
      following: false,
      musicTrack: "Neon Skyline · Licensed Sync",
    },
    {
      id: "p7",
      kind: "page",
      authorUsername: "joes-pizza",
      authorName: "Joe's Pizza",
      authorAccent: "#FF4D6D",
      title: "Late slice run",
      text: "Line is long but the map says it's worth it. South Beach classic.",
      venue: "Joe's Pizza · South Beach",
      city: "Miami",
      mediaHue: "#FF4D6D",
      createdAt: h(12),
      likes: 940,
      comments: 72,
      reposts: 88,
      saves: 200,
      liked: false,
      saved: false,
      reposted: false,
      following: false,
    },
    {
      id: "p8",
      kind: "thought",
      authorUsername: "city-pulse",
      authorName: "City Pulse",
      authorAccent: "#00D4FF",
      verified: true,
      text: "CITY IS LIT 99% — 3,595 active explorers on the map right now. Where are you headed?",
      city: "Miami",
      createdAt: h(0.5),
      likes: 8900,
      comments: 1200,
      reposts: 3400,
      saves: 560,
      liked: true,
      saved: false,
      reposted: false,
      following: true,
    },
  ],
  conversations: [
    {
      id: "c1",
      username: "dj-kairo",
      name: "KAIRO",
      accent: "#00D4FF",
      lastMessage: "Pull up to the set — you're on the guest lens",
      time: "2m",
      unread: 2,
      online: true,
    },
    {
      id: "c2",
      username: "neon-lounge",
      name: "Neon Lounge",
      accent: "#FF4D6D",
      lastMessage: "VIP lane is open on the map pin",
      time: "18m",
      unread: 0,
      online: true,
    },
    {
      id: "c3",
      username: "marcus-j",
      name: "Marcus J",
      accent: "#34D399",
      lastMessage: "That repost was fire 🔥",
      time: "1h",
      unread: 0,
    },
    {
      id: "c4",
      username: "pulse-kitchen",
      name: "Pulse Kitchen",
      accent: "#FFB020",
      lastMessage: "Table for 2 still good at 10?",
      time: "3h",
      unread: 1,
    },
    {
      id: "c5",
      username: "miami-foodie",
      name: "Miami Foodie",
      accent: "#FF4D6D",
      lastMessage: "Sent you the Wynwood spot pin",
      time: "1d",
      unread: 0,
    },
  ],
  chatMessages: {
    c1: [
      { id: "m1", conversationId: "c1", fromMe: false, text: "Yo — crowd is insane tonight", time: "9:12 PM" },
      { id: "m2", conversationId: "c1", fromMe: true, text: "I see it on the map, omw", time: "9:14 PM", read: true },
      { id: "m3", conversationId: "c1", fromMe: false, text: "Pull up to the set — you're on the guest lens", time: "9:15 PM" },
    ],
    c2: [
      { id: "m4", conversationId: "c2", fromMe: false, text: "Doors just opened", time: "8:40 PM" },
      { id: "m5", conversationId: "c2", fromMe: true, text: "Need the map pin again?", time: "8:42 PM", read: true },
      { id: "m6", conversationId: "c2", fromMe: false, text: "VIP lane is open on the map pin", time: "8:43 PM" },
    ],
    c3: [
      { id: "m7", conversationId: "c3", fromMe: false, text: "That repost was fire 🔥", time: "7:20 PM" },
    ],
    c4: [
      { id: "m8", conversationId: "c4", fromMe: true, text: "Table for 2 still good at 10?", time: "4:10 PM", read: true },
    ],
    c5: [
      { id: "m9", conversationId: "c5", fromMe: false, text: "Sent you the Wynwood spot pin", time: "Yesterday" },
    ],
  },
  notifications: [
    { id: "n1", type: "live", username: "dj-kairo", name: "KAIRO", accent: "#00D4FF", text: "went live at LIV Nightclub — 14K watching", time: "2m", read: false },
    { id: "n2", type: "like", username: "marcus-j", name: "Marcus J", accent: "#34D399", text: "liked your thought", time: "15m", read: false, postId: "p3" },
    { id: "n3", type: "follow", username: "miami-foodie", name: "Miami Foodie", accent: "#FF4D6D", text: "started following you", time: "1h", read: false },
    { id: "n4", type: "comment", username: "neon-lounge", name: "Neon Lounge", accent: "#FF4D6D", text: "commented: \"See you on the map tonight\"", time: "2h", read: true, postId: "p1" },
    { id: "n5", type: "repost", username: "nova-games", name: "Nova", accent: "#A855F7", text: "reposted your city update", time: "3h", read: true, postId: "p6" },
    { id: "n6", type: "story", username: "pulse-kitchen", name: "Pulse Kitchen", accent: "#FFB020", text: "added to their story", time: "5h", read: true },
    { id: "n7", type: "mention", username: "city-pulse", name: "City Pulse", accent: "#00D4FF", text: "mentioned you in a city pulse", time: "6h", read: true },
    { id: "n8", type: "city", username: "city-pulse", name: "City Pulse", accent: "#00D4FF", text: "Miami hit 99% city energy — you're in the surge zone", time: "8h", read: true },
    { id: "n9", type: "invite", username: "neon-lounge", name: "Neon Lounge", accent: "#FF4D6D", text: "invited you to a map event · Brickell Night", time: "1d", read: true },
  ],
};
