import type { VerifiedBusiness } from "./businesses";

const now = Date.now();

function sig(type: "live" | "checkin" | "momentum" | "video" | "unique_posters", weight: number, minutesAgo: number) {
  return { type, weight, timestamp: now - minutesAgo * 60_000 };
}

/** Verified NYC anchors — real street grid, stylized 3D map (not live GPS) */
export const NYC_VERIFIED_BUSINESSES: VerifiedBusiness[] = [
  {
    slug: "msg-garden",
    name: "Madison Square Garden",
    districtId: "arena",
    districtName: "Midtown",
    tagline: "Knicks night · sold out energy",
    description: "The world's most famous arena. Tonight the city converges on 34th Street.",
    verified: true,
    accentColor: "#FF4D6D",
    energy: 92,
    mapPosition: { x: 50, y: 40 },
    hours: "Doors 6PM · Show 8PM",
    live: true,
    vibeSignals: [sig("live", 1.2, 1), sig("checkin", 1, 4), sig("momentum", 1.1, 6)],
    friendsCheckedIn: ["Jay", "Mia"],
    liveContent: [{ id: "n1", type: "live", title: "Pre-show tunnel", user: "Jay", signals: [sig("live", 1, 1)] }],
    updates: [{ id: "u1", text: "Main concourse at peak capacity", minutesAgo: 5 }],
    todayEvents: [{ id: "e1", title: "Knicks vs Celtics", time: "8:00 PM" }],
  },
  {
    slug: "barclays-center",
    name: "Barclays Center",
    districtId: "arena",
    districtName: "Brooklyn",
    tagline: "Brooklyn is loud tonight",
    description: "Atlantic Ave pulsing. Verified venue with live crowd signals from the plaza.",
    verified: true,
    accentColor: "#00D4FF",
    energy: 86,
    mapPosition: { x: 62, y: 55 },
    hours: "Doors 7PM",
    live: true,
    vibeSignals: [sig("checkin", 1, 2), sig("momentum", 0.95, 8)],
    friendsCheckedIn: ["Dev"],
    liveContent: [],
    updates: [{ id: "u1", text: "Plaza watch party live", minutesAgo: 12 }],
    todayEvents: [{ id: "e1", title: "Nets home stand", time: "7:30 PM" }],
  },
  {
    slug: "carbone-nyc",
    name: "Carbone",
    districtId: "food",
    districtName: "Greenwich Village",
    tagline: "Reservations surging",
    description: "Verified restaurant hotspot. The dining room is the story tonight.",
    verified: true,
    accentColor: "#FF7A00",
    energy: 78,
    mapPosition: { x: 44, y: 48 },
    hours: "5PM – 11PM",
    waitTime: "~45 min bar",
    live: false,
    vibeSignals: [sig("checkin", 0.85, 10), sig("unique_posters", 0.7, 20)],
    friendsCheckedIn: ["Sasha"],
    liveContent: [],
    updates: [{ id: "u1", text: "Bar seats just opened", minutesAgo: 8 }],
    todayEvents: [],
  },
  {
    slug: "marquee-nyc",
    name: "Marquee",
    districtId: "nightlife",
    districtName: "Chelsea",
    tagline: "DJ set · line moving",
    description: "Verified nightclub on the west side. Neon spilling onto 10th Ave.",
    verified: true,
    accentColor: "#A855F7",
    energy: 90,
    mapPosition: { x: 48, y: 52 },
    hours: "10PM – 4AM",
    coverCharge: "$40",
    live: true,
    vibeSignals: [sig("live", 1.1, 2), sig("checkin", 0.9, 5)],
    friendsCheckedIn: ["Tyler", "Ren"],
    liveContent: [{ id: "n2", type: "live", title: "Main room", user: "Ren", signals: [sig("live", 1, 1)] }],
    updates: [{ id: "u1", text: "VIP line 20 min", minutesAgo: 3 }],
    todayEvents: [{ id: "e1", title: "Resident DJ", time: "12:00 AM" }],
  },
  {
    slug: "summit-vanderbilt",
    name: "SUMMIT One Vanderbilt",
    districtId: "shopping",
    districtName: "Midtown East",
    tagline: "Views + city glow",
    description: "Verified experience deck. The skyline story everyone searches.",
    verified: true,
    accentColor: "#00D4FF",
    energy: 74,
    mapPosition: { x: 54, y: 38 },
    hours: "9AM – 12AM",
    live: false,
    vibeSignals: [sig("checkin", 0.8, 15), sig("video", 0.75, 18)],
    friendsCheckedIn: [],
    liveContent: [],
    updates: [{ id: "u1", text: "Golden hour tickets selling fast", minutesAgo: 25 }],
    todayEvents: [],
  },
  {
    slug: "soho-house-nyc",
    name: "Soho House NY",
    districtId: "nightlife",
    districtName: "Meatpacking",
    tagline: "Members & creators live",
    description: "Verified creator hub. Rooftop streams and city conversations.",
    verified: true,
    accentColor: "#E8B4B8",
    energy: 81,
    mapPosition: { x: 42, y: 56 },
    hours: "Members · 7AM – 2AM",
    live: true,
    vibeSignals: [sig("live", 0.9, 4), sig("unique_posters", 0.85, 12)],
    friendsCheckedIn: ["Luna"],
    liveContent: [{ id: "n3", type: "live", title: "Rooftop Q&A", user: "Luna", signals: [sig("live", 1, 2)] }],
    updates: [{ id: "u1", text: "Creator lounge open", minutesAgo: 14 }],
    todayEvents: [{ id: "e1", title: "Industry mixer", time: "9:00 PM" }],
  },
];
