import type { LucideIcon } from "lucide-react";
import {
  BookOpen,
  Camera,
  Car,
  ChefHat,
  Clapperboard,
  Cpu,
  Dumbbell,
  Film,
  Footprints,
  Gamepad2,
  Globe,
  Handshake,
  Headphones,
  Heart,
  Map,
  Megaphone,
  Mic2,
  Moon,
  Music2,
  Palette,
  PartyPopper,
  PawPrint,
  Plane,
  Radio,
  Scissors,
  Shirt,
  Sparkles,
  Star,
  Store,
  Sun,
  TrendingUp,
  Trophy,
  Users,
  UtensilsCrossed,
  Video,
  Wallet,
  Wrench,
  Zap,
  Wine,
} from "lucide-react";
import type { IdentityInterestOption } from "@/lib/identity/identityInterests";

const ICONS: Record<IdentityInterestOption["icon"], LucideIcon> = {
  gamepad: Gamepad2,
  trophy: Trophy,
  music: Music2,
  plane: Plane,
  camera: Camera,
  food: UtensilsCrossed,
  car: Car,
  cpu: Cpu,
  business: TrendingUp,
  clapperboard: Clapperboard,
  dumbbell: Dumbbell,
  shirt: Shirt,
  film: Film,
  moon: Moon,
  footprints: Footprints,
  paw: PawPrint,
  mic: Mic2,
  headphones: Headphones,
  sparkles: Sparkles,
  scissors: Scissors,
  palette: Palette,
  video: Video,
  users: Users,
  heart: Heart,
  star: Star,
  map: Map,
  store: Store,
  chef: ChefHat,
  wine: Wine,
  party: PartyPopper,
  radio: Radio,
  zap: Zap,
  globe: Globe,
  handshake: Handshake,
  megaphone: Megaphone,
  book: BookOpen,
  wallet: Wallet,
  wrench: Wrench,
  sun: Sun,
};

export function getInterestIcon(icon: IdentityInterestOption["icon"]): LucideIcon {
  return ICONS[icon] ?? Sparkles;
}
